feat: [DAD-310] make installation compatible with edx/configuration/roles/edx_django_service
strata-kk/lti-producer pull request #2
Opened 2022-03-18 18:01 UTC by a-kryachko

2022-03-21 09:28 UTC, regisb reviewed
I'm not proposing any major change here. But I'm a bit surprised: are you running Open edX with the native installation, and not Tutor? This means that Open edX will be extremely difficult to upgrade in the future, as the native installation is no longer supported.

2022-03-21 09:28 UTC, regisb commented on Makefile
> +	pip-compile --output-file=requirements/base.txt setup.cfg
I think that the base.txt file should be compiled before the dev.txt file, because the dev.txt file depends on base.txt. (and same thing below)

2022-03-21 09:28 UTC, regisb commented on manage.py
> +standalone/producer/manage.py
If you really need to symlink all the data from the standalone producer project to the root folder, then I suggest that you simply move the files (remember to modify the README).

2022-03-21 09:28 UTC, regisb commented on standalone/producer/settings/base.py
> +    MIDDLEWARE.append("django.middleware.clickjacking.XFrameOptionsMiddleware")
This setting should probably be documented in the README because it will prevent the producer from being embedded within iframes.

2022-03-21 09:28 UTC, regisb commented on standalone/producer/settings/prod.py
> +        vars().update(yaml.safe_load(f))
Are you sure you want to do that? This has historically been a terrible pattern within edx-platform, and I don't think we should start using it here.

2022-03-21 10:30 UTC, a-kryachko commented on Makefile
> +	pip-compile --output-file=requirements/base.txt setup.cfg
As far as I see, both of `dev.txt` and `base.txt` and based on `setup.cfg` and does not have includes.
I has reverted this change to not be confused.

2022-03-21 10:36 UTC, a-kryachko commented on standalone/producer/settings/base.py
> +    MIDDLEWARE.append("django.middleware.clickjacking.XFrameOptionsMiddleware")
My changes does not change current configuration flow (by default `ENABLE_CLICKJACKING_MIDDLEWARE = True`). But it allows to control the inclusion of `XFrameOptionsMiddleware` via environment variable or via prod configuration YAML file.

2022-03-21 10:48 UTC, a-kryachko commented on standalone/producer/settings/prod.py
> +        vars().update(yaml.safe_load(f))
The main purpose of this PR is to make this repo compatible with [edx_django_service](https://github.com/openedx/configuration/tree/open-release/maple.master/playbooks/roles/edx_django_service) for easy integration to Native Install deployment (currently used on Strata KK OpenEdx platform).

Refactoring of code in this repo can be difficult to be able to set all required DJango variables via environment variables. Here the example of required settings to be able to run application in production - https://github.com/a-kryachko/lti-producer/blob/a-kraychko/DAD-310/lti-producer.yml.sample

2022-03-22 08:37 UTC, regisb commented on Makefile
> +	pip-compile --output-file=requirements/base.txt setup.cfg
You are right, actually dev.txt does not depend on base.txt. Still, it's probably better to compile the base file before the development file.

2022-03-22 08:44 UTC, regisb commented on manage.py
> +standalone/producer/manage.py
All manage.py commands should be run using the script from `standalone/producer/manage.py`. For instance, in production:

    DJANGO_SETTINGS_MODULE=settings.prod ./standalone/producer/manage.py shell

2022-03-22 08:46 UTC, regisb commented on standalone/producer/settings/base.py
> +    MIDDLEWARE.append("django.middleware.clickjacking.XFrameOptionsMiddleware")
I suggest you write the following:

```
if "ENABLE_CLICKJACKING_MIDDLEWARE" in os.environ:
    MIDDLEWARE.append("django.middleware.clickjacking.XFrameOptionsMiddleware")
```

And then document the impact of the ENABLE_CLICKJACKING_MIDDLEWARE environment variable in the readme.

2022-03-22 08:49 UTC, regisb commented on standalone/producer/settings/prod.py
> +        vars().update(yaml.safe_load(f))
Many variables in that file should be defined as sensible defaults in prod.py. Then, the few variables that need to be overridden (secret key, sentry DSN, etc.) can be read either from environment variables.
The blank `vars().update(...)` statement in many Open edX projects is actually an incentive to not create good default settings.

2022-03-22 09:42 UTC, a-kryachko commented on manage.py
> +standalone/producer/manage.py
This requires forking and customizing of github.com/openedx/configuration. There is a single task in `edx_django_service` role that requires `manage.py` to be in repository root - https://github.com/openedx/configuration/blob/open-release/maple.master/playbooks/roles/edx_django_service/tasks/main.yml#L357 . Symlink was created to omit this fail.

2022-03-22 09:47 UTC, a-kryachko commented on standalone/producer/settings/base.py
> +    MIDDLEWARE.append("django.middleware.clickjacking.XFrameOptionsMiddleware")
@Alain1405 Can we reassign code refactoring to developer?

2022-03-22 09:47 UTC, a-kryachko commented on standalone/producer/settings/prod.py
> +        vars().update(yaml.safe_load(f))
@Alain1405 Can we reassign code refactoring to developer?

2022-03-23 09:30 UTC, Alain1405 requested changes

2022-03-23 09:30 UTC, Alain1405 commented on manage.py
> +standalone/producer/manage.py
There was a misunderstanding. We are going to release this as a standalone app and we don't need these changes.

2022-03-23 09:30 UTC, Alain1405 commented on requirements/base.txt
> +django==4.0.3
We should not need to upgrade to Django 4. Vlad will check

2022-03-23 09:30 UTC, Alain1405 commented on standalone/producer/settings/base.py
> +    MIDDLEWARE.append("django.middleware.clickjacking.XFrameOptionsMiddleware")
I will let Vlad decide how to handle this

2022-03-23 09:30 UTC, Alain1405 commented on standalone/producer/settings/prod.py
> +        vars().update(yaml.safe_load(f))
Will not be needed

2022-03-23 09:30 UTC, Alain1405 commented on standalone/producer/settings/prod.py
> +if not ENABLE_CLICKJACKING_MIDDLEWARE:
Redundant

2022-03-23 09:30 UTC, Alain1405 commented on standalone/producer/settings/prod.py
> +    INSTALLED_APPS.append("muxltiproducer")
@regisb can you explain how you integrated mux-producer in your installation? As I understand, this code is not needed.

2022-03-23 10:15 UTC, a-kryachko commented on requirements/base.txt
> +django==4.0.3
Vlad JFYI:
According to https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-CACHES-BACKEND
```
Changed in Django 4.0:
The RedisCache backend was added.
```

2022-03-24 08:50 UTC, regisb commented on standalone/producer/settings/prod.py
> +    INSTALLED_APPS.append("muxltiproducer")
Actually this piece of code is needed, but I suggest to add it to a private.py file, such that the prod.py fle can be used even if muxltiproducer is not installed. I forwarded you a copy of my own private.py file, and it includes secrets from Mux so I can't publish it here.

2022-05-05 07:24 UTC, closed without merging